"""
English subject descriptions for each icon.
The prompt is built as: "[subject], [visual detail from icons.md], [style]"
Subject must clearly name the object in English first.
"""

SUBJECTS = {
    # --- Bouteilles boissons ---
    "bouteille-biere":      "amber beer bottle with metal cap",
    "bouteille-cidre":      "green glass cider bottle",
    "bouteille-cola":       "dark cola soda bottle",
    "bouteille-fanta":      "orange soda bottle",
    "bouteille-icetea":     "golden iced tea bottle",
    "bouteille-limonade":   "yellow lemonade bottle",
    "bouteille-vin-rouge":  "dark bordeaux red wine bottle",
    "bouteille-vin-blanc":  "pale green white wine bottle",
    "bouteille-rhum":       "dark brown rum spirits bottle",
    "bouteille-sirop":      "tall slim red syrup bottle",
    "bouteille-huile":      "golden olive oil bottle",
    # --- Sauces ---
    "bouteille-sauce-rouge":   "red ketchup squeeze bottle",
    "bouteille-sauce-jaune":   "yellow mayonnaise squeeze bottle",
    "bouteille-sauce-brune":   "brown barbecue sauce bottle",
    "bouteille-sauce-verte":   "green pesto sauce jar",
    "bouteille-sauce-orange":  "orange tikka masala sauce bottle",
    # --- Conserves ---
    "conserve-legumes":    "green label vegetable tin can",
    "conserve-tomate":     "red label tomato tin can",
    "conserve-poisson":    "blue label fish tin can",
    "conserve-soupe":      "orange label soup tin can",
    "conserve-cassoulet":  "brown label cassoulet tin can",
    "conserve-plat":       "generic ready meal tin can",
    # --- Fromages ---
    "fromage-rond":        "round flat cheese wheel like camembert",
    "fromage-bloc":        "rectangular yellow cheese block",
    "fromage-rape":        "pile of grated shredded cheese",
    "fromage-frais":       "white fresh cheese pot with lid",
    "fromage-burger":      "square yellow cheese slice",
    "fromage-chevre":      "white goat cheese log",
    "fromage-bleu":        "blue cheese wedge with mold veins",
    "fromage-moule":       "fresh mozzarella ball in water",
    "fromage-morbier":     "cheese slice with black horizontal line in center",
    "fromage-munster":     "orange rind round munster cheese",
    "babybel":             "small red wax-coated round cheese",
    "fromage-raclette":    "half wheel of raclette cheese",
    "cheddar":             "orange cheddar cheese block",
    "parmesan":            "rough granular parmesan cheese wedge",
    # --- Charcuterie / Viandes / Poissons ---
    "chorizo":             "sliced chorizo sausage rounds",
    "saucisson":           "sliced salami sausage rounds",
    "jambon":              "pink folded ham slice",
    "bacon":               "two striped bacon rashers",
    "lardon":              "small pink bacon lardons cubes in tray",
    "saucisse":            "curved pink sausage",
    "saucisse-chipolata":  "thin beige chipolata sausage",
    "saucisse-merguez":    "thin dark red merguez sausage",
    "steak-hache":         "round ground beef patty with grill marks",
    "poulet":              "golden chicken drumstick with bone",
    "agneau":              "lamb chop cutlet with bone",
    "porc":                "pork roast slice",
    "pate":                "oval pâté tin can",
    "rillettes":           "glass jar of salmon rillettes spread",
    "cordon-bleu":         "breaded golden cordon bleu escalope",
    "saumon":              "pink salmon fillet with skin",
    "moules":              "open black mussel shell with orange flesh",
    "poisson-pane":        "golden breaded fish fillet rectangle",
    # --- Épicerie sèche ---
    "pates":               "pasta package with penne visible through window",
    "macaroni":            "macaroni pasta package",
    "nouilles":            "asian noodles ramen block package",
    "lasagnes":            "flat lasagna pasta sheets package",
    "ravioli":             "ravioli pasta package",
    "riz":                 "transparent rice bag with white grains",
    "semoule":             "couscous semolina package",
    "lentilles":           "green lentils bag",
    "farine":              "white flour bag with wheat logo",
    "sucre":               "white sugar bag",
    "sucre-morceau":       "box of white sugar cubes",
    "chapelure":           "golden breadcrumbs package",
    "puree-instant":       "instant mashed potato flakes sachet",
    "potee-mais-popcorn":  "popcorn bag or corn box",
    # --- Boulangerie ---
    "pain":                "golden french baguette bread",
    "pain-mie":            "sliced sandwich bread loaf in bag",
    "pain-burger":         "round sesame seed burger bun",
    "pain-lait":           "oval golden brioche milk roll",
    "brioche":             "braided golden brioche loaf",
    "galette-kebab":       "round flat pita flatbread",
    "pate-pizza":          "ball of pizza dough",
    "pate-feuilletee":     "rolled out puff pastry sheet",
    # --- Produits laitiers ---
    "lait":                "white milk carton Tetra Pak",
    "lait-coco":           "white coconut milk tin can",
    "beurre":              "butter block wrapped in golden paper",
    "creme-fraiche":       "white sour cream pot with lid",
    "creme-liquide":       "small cream UHT carton",
    "oeuf":                "egg box with six eggs",
    "yaourt":              "plastic yogurt pot with foil lid",
    "yop":                 "small drinkable yogurt bottle",
    "fromage-blanc":       "white fromage blanc large tub",
    "chantilly":           "whipped cream aerosol spray can",
    # --- Épices & condiments ---
    "epice":               "small glass spice jar with red lid",
    "herbe":               "fresh green herb bunch",
    "poivre":              "wooden pepper mill grinder",
    "sel":                 "blue salt box",
    "ail":                 "garlic head bulb",
    "oignon":              "brown onion bulb",
    "bouillon":            "golden bouillon cube in foil wrapper",
    "moutarde":            "yellow mustard pot jar",
    # --- Légumes & Fruits ---
    "tomate":              "round red tomato with green stem",
    "carotte":             "orange carrot with green leaves",
    "pomme-de-terre":      "beige potato",
    "aubergine":           "purple eggplant aubergine",
    "courgette":           "green zucchini courgette",
    "brocoli":             "green broccoli floret",
    "poivron":             "shiny red bell pepper",
    "salade":              "green lettuce head from above",
    "champignon":          "white button mushroom",
    "citron":              "yellow lemon",
    "cornichon":           "green gherkin pickles jar",
    "avocat":              "avocado half with brown pit",
    "banane":              "yellow curved banana",
    "poire":               "yellow green pear with stem",
    "pomme":               "shiny red apple with leaf",
    "kiwi":                "kiwi fruit cut in half showing green flesh",
    "fruits":              "fruit basket with apple banana and grapes",
    # --- Apéro snacks ---
    "chips":               "inflated chips snack bag",
    "cacahuete":           "peanuts in shell",
    "pistache":            "green pistachio nuts",
    "noisette":            "hazelnuts with leaves",
    "noix-cajou":          "cashew nuts",
    # --- Petit-déjeuner / sucré ---
    "cereales":            "cereal box with corn flakes",
    "barre-cereales":      "wrapped cereal granola bar",
    "chocolat":            "dark chocolate bar with broken square",
    "nutella":             "hazelnut chocolate spread jar",
    "confiture":           "strawberry jam glass jar with red lid",
    "creme-marron":        "chestnut cream tube",
    "beurre-cacahuete":    "peanut butter open jar",
    "miel":                "hexagonal golden honey jar",
    "bonbons":             "colorful candy sweets bag",
    "gateaux":             "cookies biscuits package with window",
    "madeleines":          "madeleines shell cakes package",
    "compote":             "apple sauce squeeze pouch",
    "flan-sachet":         "flan custard powder preparation sachet",
    "creme-anglaise":      "custard sauce small carton",
    "glace":               "ice cream tub with lid",
    "cafe":                "instant coffee glass jar with golden lid",
    "capuccino":           "cappuccino powder sachet",
    "the":                 "tea box with tea bag hanging",
    # --- Surgelés ---
    "frites":              "frozen french fries bag",
    "pizza":               "frozen pizza box",
    "gyoza":               "two gyoza dumplings crescent shaped",
    "nuggets":             "three golden breaded chicken nuggets",
    "rosti":               "golden crispy potato rosti cake",
    # --- Hygiène ---
    "brosse-dents":        "blue and white toothbrush",
    "dentifrice":          "toothpaste tube",
    "coton-tige":          "cotton swab box with cotton swab",
    "coton":               "cotton pads discs stack",
    "deodorant":           "roll-on deodorant bottle",
    "gel-douche":          "shower gel bottle with flip cap",
    "shampoing":           "shampoo bottle",
    "spray-demelant":      "hair detangler spray bottle",
    "creme-main":          "hand cream tube",
    "pansement":           "bandage plaster box",
    "savon-liquide":       "liquid soap pump dispenser",
    "gel-hydroalcoolique": "hand sanitizer gel bottle",
    "dissolvant":          "nail polish remover small bottle",
    # --- Entretien ---
    "produit-vaisselle":   "green dish soap washing liquid bottle",
    "lessive":             "laundry detergent box or bottle",
    "tablettes-lv":        "dishwasher tablets package with tablet",
    "spray-nettoyant":     "blue cleaning spray bottle with trigger",
    "antikal":             "descaler spray bottle",
    "destop":              "drain unblocker bottle",
    "eponge":              "green and yellow kitchen sponge",
    "papier-aluminium":    "aluminum foil roll with unfolded corner",
    "papier-cuisson":      "baking parchment paper roll",
    "papier-film":         "transparent plastic cling film roll",
    "pq":                  "toilet paper roll",
    "sopalin":             "paper towel kitchen roll",
    "serviette":           "folded paper napkins pack",
    "sac-poubelle":        "trash garbage bag roll",
    "sac-congelation":     "transparent freezer zip bag",
    "sac-aspirateur":      "vacuum cleaner dust bag",
    "lingettes":           "wet wipes pack with flip lid",
    "sel-lv":              "dishwasher salt box",
    # --- Divers ---
    "pile":                "AA battery",
    "briquet":             "plastic lighter",
    "colle":               "glue tube with red cap",
    "tupperware":          "transparent plastic food container with lid",
}
